openapi: 3.0.0
info:
  title: Company Campaign API
  description: API para gerenciamento de campanhas de empresas.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
paths:
  /company-campaign:
    post:
      summary: Cria uma nova campanha de empresa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCompanyCampaignDTO'
      responses:
        '201':
          description: Campanha criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCompanyCampaignDTO'
        '400':
          description: Dados de campanha inválidos
        '500':
          description: Erro no servidor
    get:
      summary: Obtém uma lista de campanhas de empresas
      parameters:
        - in: query
          name: start_cursor
          schema:
            type: string
          description: Cursor para paginação dos dados
      responses:
        '200':
          description: Lista de campanhas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreateCompanyCampaignDTO'
        '500':
          description: Erro no servidor
  /company-campaign/{id}:
    patch:
      summary: Atualiza uma campanha de empresa existente
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID da campanha a ser atualizada
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCompanyCampaignDTO'
      responses:
        '200':
          description: Campanha atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateCompanyCampaignDTO'
        '400':
          description: ID ou dados inválidos
        '500':
          description: Erro no servidor
    delete:
      summary: Remove uma campanha de empresa
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID da campanha a ser removida
      responses:
        '200':
          description: Campanha removida com sucesso
        '400':
          description: ID inválido
        '500':
          description: Erro no servidor
components:
  schemas:
    CreateCompanyCampaignDTO:
      type: object
      properties:
        company:
          type: string
          description: Nome da empresa
        campaign:
          type: string
          description: Nome da campanha
        content:
          type: string
          description: Conteúdo da campanha
        description:
          type: string
          description: Descrição da campanha
        image:
          type: string
          description: URL da imagem da campanha
        language:
          type: string
          description: Idioma da campanha
        plannedDate:
          type: string
          format: date-time
          description: Data planejada para a campanha
        where:
          type: string
          description: Local de execução da campanha
        imageContent:
          type: string
          description: Conteúdo da imagem da campanha
    UpdateCompanyCampaignDTO:
      type: object
      properties:
        company:
          type: string
          description: Nome da empresa
        campaign:
          type: string
          description: Nome da campanha
        content:
          type: string
          description: Conteúdo da campanha
        description:
          type: string
          description: Descrição da campanha
        image:
          type: string
          description: URL da imagem da campanha
        language:
          type: string
          description: Idioma da campanha
        plannedDate:
          type: string
          format: date-time
          description: Data planejada para a campanha
        where:
          type: string
          description: Local de execução da campanha
        imageContent:
          type: string
          description: Conteúdo da imagem da campanha
